kind: Service
apiVersion: v1
metadata:
  name: gocd-server
spec:
  selector:
    app:  gocd-server
  type:  LoadBalancer
  ports:
  - name:  http
    port:  8153
    targetPort: http
  - name: https
    port: 8154
    targetPort: https