apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: selenium-node-chrome
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: selnium-node-chrome
    spec:
      containers:
      - name: selenium-node-chrome
        image: selenium/NodeChrome